
- name: Copy cert to /etc/openldap/cacerts
  become: yes
  become_method: sudo
  template: src=/etc/ansible/confFiles/root_cert.pem.j2 dest=/etc/openldap/cacerts/root_cert.pem

- name: Get the hash
  become: yes
  become_method: sudo
  command: openssl x509 -noout -hash -in /etc/openldap/cacerts/root_cert.pem
  register: hash

- name: Set up link
  become: yes
  become_method: sudo 
  command: ln -s /etc/openldap/cacerts/root_cert.pem /etc/openldap/cacerts/{{ hash.stdout }}.0
