
- name: Make copy of Kerberos conf file
  command: cp /etc/krb5.conf /etc/krb5.conf.{{ date }}

- name: Add new kerberos conf file 
  template: src=/etc/ansible/confFiles/krb5.conf.j2 dest=/etc/krb5.conf
                owner=root group=root mode=0600
- name: Restorecon kerberos conf file
  command: sudo /sbin/restorecon /etc/krb5.conf

- name: Create keytab
  command: sudo net ads -U svc_sssd-auth keytab create

- name: Join client to domain
  command: sudo net ads join -U svc_sssd-auth  #Prod servers need specific OU's
