
- name: Install SSSD
  yum: pkg={{ item }} state=present
  with_items:
        - sssd
        - sssd-tools
        - samba
        - oddjob
        - oddjob-mkhomedir

- name: Use DC as DNS servers
  command: cp /etc/resolv.conf /etc/resolv.conf.{{ date }}
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: Configure Samba
  command: cp /etc/samba/smb.conf /etc/samba/smb.conf.{{ date }}
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf
  notify: restart samba

- name: Configure Kerberos
  command: cp /etc/krb5.conf /etc/krb5.conf.{{ date }}
  template: src=krb5.conf.j2 dest=/etc/krb5.conf
                owner=root group=root mode=0600
  command: sudo /sbin/restorecon /etc/krb5.conf

- name: Create keytab
  command: sudo net ads -U svc_sssd-auth keytab create

- name: Join client to domain
  command: sudo net ads join -U svc_sssd-auth  #Prod servers need to specific OU's

- name: Configure PAM to use SSSD for authentication
  command: cp /etc/pam.d/system-auth /etc/pam.d/system-auth.{{ date }}
  template: src=system-auth.j2 dest=/etc/pam.d/system-auth

- name: Configure NSS
  command: cp /etc/nsswitch.conf /etc/nsswitch.conf.{{ date }}
  template: src=nsswitch.conf.j2 dest=/etc/nsswitch.conf

- name: Configure SSSD to use AD for authentication
  command: cp /etc/sssd/sssd.conf /etc/sssd/sssd.conf.{{ date }}
  template: src=sssd.conf dest=/etc/sssd/sssd.conf
                owner=root group=root mode=0600
  command: sudo /sbin/restorecon /etc/sssd/sssd.conf
  command: /sbin/chkconfig smb on
  command: /sbin/chkconfig sssd on
  notify: restart sssd

- name : Ensure SSSD is started
  service: name=sssd state=started enabled=yes
