- name: Make copy of NSS conf file
  command: cp /etc/nsswitch.conf /etc/nsswitch.conf.{{ date }}
  
- name: Add new NSS conf file
  template: src=/etc/ansible/confFiles/nsswitch.conf.j2 dest=/etc/nsswitch.conf
