- name: Make copy of current pam.d/system-auth
  command: cp /etc/pam.d/system-auth /etc/pam.d/system-auth.{{ date }}

- name: Add new pam.d/system-auth file
  template: src=/etc/ansible/confFiles/system-auth.j2 dest=/etc/pam.d/system-auth
