- name: Make copy of resolv conf file
  command: cp /etc/resolv.conf /etc/resolv.conf.{{ date }}

- name: Add new resolv conf file
  template: src=/etc/ansible/confFiles/resolv.conf.j2 dest=/etc/resolv.conf
