
- name: Make copy of sssd conf file 
  command: cp /etc/sssd/sssd.conf /etc/sssd/sssd.conf.{{ date }}

- name: Add new sssd conf file
  template: src=/etc/ansible/confFiles/sssd.conf.j2 dest=/etc/sssd/sssd.conf
                owner=root group=root mode=0600

- name: Restorecon sssd.conf
  command: sudo /sbin/restorecon /etc/sssd/sssd.conf

- name: Check config on for sssd
  command: /sbin/chkconfig sssd on
  notify: restart sssd

- name : Ensure SSSD is started
  service: name=sssd state=started enabled=yes
